file(GLOB SOURCES_CPP RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cpp")
file(GLOB_RECURSE HEADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.h")
file(GLOB_RECURSE HEADERS_INL RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.inl")

if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")

file(GLOB SOURCES_ASM RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "asm/win64/*.asm")

elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")

if(${ARCHITECTURE} STREQUAL "x86")

file(GLOB SOURCES_ASM RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "asm/linux32/*.asm")

elseif(${ARCHITECTURE} STREQUAL "x86-64")

file(GLOB SOURCES_ASM RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "asm/linux64/*.asm")

endif()

elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")

file(GLOB SOURCES_ASM RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "asm/iOS/*.asm")

endif()

message("asm: "${SOURCES_ASM})

set(SOURCES ${SOURCES_CPP} ${SOURCES_ASM})